sudo: required
language: java
jdk: oraclejdk8

services:
  - docker
  
before_script:
  - chmod +x mvnw

script:
  - ./mvnw clean install -B
  
after_success:
  - docker login -u $DOCKER_USER -p $DOCKER_PASS
  - docker build -t jaikuai/footsone .
  - docker push jaikuai/footsone