sudo: required
language: java
jdk: oraclejdk8

services:
  - docker
  
after_success:
- docker login -u $DOCKER_USER -p $DOCKER_PASS
- docker build -t jaikuai/footsone .
- docker push jaikuai/footsone