sudo: required
language: java
install: true
jdk: oraclejdk8

services:
  - docker
  
before_install:
  - chmod a+x ./mvnw

script:
  - ./mvnw clean install -B
  
after_success:
  - docker login -u $DOCKER_USER -p $DOCKER_PASS
  - docker build -t jaikuai/footsone .
  - docker push jaikuai/footsone