sudo: required
language: java
jdk: oraclejdk8

script:
- ./mvnw clean install -B
 
services:
  - docker
  
after_success:
- docker login -u $DOCKER_USER -p $DOCKER_PASS
- docker build -t jaikuai/footsone .
- docker push jaikuai/footsone